# ==============================
# DEV PROFILE
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5

# Logging
logging.level.com.example.CampusConnect=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# Cookies (DEV)
# ===============================

cookie.secure=false
cookie.same-site=Lax
cookie.domain=

# ===============================
# JWT Expiration
# ===============================

jwt.access-expiration=900000
jwt.refresh-expiration=604800000

# Dev tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ==============================
# Google OAuth2
# ==============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google