# =========================
# PROD PROFILE
# =========================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

cookie.secure=true

logging.level.com.example.CampusConnect=INFO
logging.level.org.hibernate.SQL=WARN

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
