# ==============================
# PROD PROFILE
# ==============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=15

# Logging
logging.level.com.example.CampusConnect=INFO
logging.level.org.hibernate.SQL=WARN

# Cookies
cookie.secure=true

# JWT (optional)
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# Disable devtools
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false