# ==============================
# DEV PROFILE
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5

# Logging
logging.level.com.example.CampusConnect=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cookies
cookie.secure=false

# JWT (optional if needed)
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# Dev tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true