# =========================
# DEV PROFILE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cookie.secure=false

logging.level.com.example.CampusConnect=DEBUG
logging.level.org.hibernate.SQL=DEBUG
